# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hazard_perception_v0/Hazard3D.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class Hazard3D(genpy.Message):
  _md5sum = "2af06c5e740031a3e6b4af89771e5573"
  _type = "hazard_perception_v0/Hazard3D"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint32 id
geometry_msgs/Point position
float32 confidence
uint32 observation_count
bool confirmed
string localization_source

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['id','position','confidence','observation_count','confirmed','localization_source']
  _slot_types = ['uint32','geometry_msgs/Point','float32','uint32','bool','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,position,confidence,observation_count,confirmed,localization_source

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Hazard3D, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.confidence is None:
        self.confidence = 0.
      if self.observation_count is None:
        self.observation_count = 0
      if self.confirmed is None:
        self.confirmed = False
      if self.localization_source is None:
        self.localization_source = ''
    else:
      self.id = 0
      self.position = geometry_msgs.msg.Point()
      self.confidence = 0.
      self.observation_count = 0
      self.confirmed = False
      self.localization_source = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_I3dfIB().pack(_x.id, _x.position.x, _x.position.y, _x.position.z, _x.confidence, _x.observation_count, _x.confirmed))
      _x = self.localization_source
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 37
      (_x.id, _x.position.x, _x.position.y, _x.position.z, _x.confidence, _x.observation_count, _x.confirmed,) = _get_struct_I3dfIB().unpack(str[start:end])
      self.confirmed = bool(self.confirmed)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.localization_source = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.localization_source = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_I3dfIB().pack(_x.id, _x.position.x, _x.position.y, _x.position.z, _x.confidence, _x.observation_count, _x.confirmed))
      _x = self.localization_source
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 37
      (_x.id, _x.position.x, _x.position.y, _x.position.z, _x.confidence, _x.observation_count, _x.confirmed,) = _get_struct_I3dfIB().unpack(str[start:end])
      self.confirmed = bool(self.confirmed)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.localization_source = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.localization_source = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_I3dfIB = None
def _get_struct_I3dfIB():
    global _struct_I3dfIB
    if _struct_I3dfIB is None:
        _struct_I3dfIB = struct.Struct("<I3dfIB")
    return _struct_I3dfIB
