<?xml version="1.0"?>
<package format="2">
  <name>merge_explore</name>
  <version>0.1.0</version>
  <description>Multi-floor exploration merging DWA navigation with stair climbing</description>

  <maintainer email="loser@todo.todo">loser</maintainer>
  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>rospy</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>tf</depend>

  <export>
  </export>
</package>
