// Generated by gencpp from file hazard_perception_v0/Hazard3DArray.msg
// DO NOT EDIT!


#ifndef HAZARD_PERCEPTION_V0_MESSAGE_HAZARD3DARRAY_H
#define HAZARD_PERCEPTION_V0_MESSAGE_HAZARD3DARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <hazard_perception_v0/Hazard3D.h>

namespace hazard_perception_v0
{
template <class ContainerAllocator>
struct Hazard3DArray_
{
  typedef Hazard3DArray_<ContainerAllocator> Type;

  Hazard3DArray_()
    : header()
    , hazards()  {
    }
  Hazard3DArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , hazards(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::hazard_perception_v0::Hazard3D_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::hazard_perception_v0::Hazard3D_<ContainerAllocator> >> _hazards_type;
  _hazards_type hazards;





  typedef boost::shared_ptr< ::hazard_perception_v0::Hazard3DArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hazard_perception_v0::Hazard3DArray_<ContainerAllocator> const> ConstPtr;

}; // struct Hazard3DArray_

typedef ::hazard_perception_v0::Hazard3DArray_<std::allocator<void> > Hazard3DArray;

typedef boost::shared_ptr< ::hazard_perception_v0::Hazard3DArray > Hazard3DArrayPtr;
typedef boost::shared_ptr< ::hazard_perception_v0::Hazard3DArray const> Hazard3DArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hazard_perception_v0::Hazard3DArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hazard_perception_v0::Hazard3DArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hazard_perception_v0::Hazard3DArray_<ContainerAllocator1> & lhs, const ::hazard_perception_v0::Hazard3DArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.hazards == rhs.hazards;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hazard_perception_v0::Hazard3DArray_<ContainerAllocator1> & lhs, const ::hazard_perception_v0::Hazard3DArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hazard_perception_v0

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hazard_perception_v0::Hazard3DArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hazard_perception_v0::Hazard3DArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hazard_perception_v0::Hazard3DArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hazard_perception_v0::Hazard3DArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hazard_perception_v0::Hazard3DArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hazard_perception_v0::Hazard3DArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hazard_perception_v0::Hazard3DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "45285fb7a9658ae251ee2d8e7e727d24";
  }

  static const char* value(const ::hazard_perception_v0::Hazard3DArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x45285fb7a9658ae2ULL;
  static const uint64_t static_value2 = 0x51ee2d8e7e727d24ULL;
};

template<class ContainerAllocator>
struct DataType< ::hazard_perception_v0::Hazard3DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hazard_perception_v0/Hazard3DArray";
  }

  static const char* value(const ::hazard_perception_v0::Hazard3DArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hazard_perception_v0::Hazard3DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"Hazard3D[] hazards\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: hazard_perception_v0/Hazard3D\n"
"uint32 id\n"
"geometry_msgs/Point position\n"
"float32 confidence\n"
"uint32 observation_count\n"
"bool confirmed\n"
"string localization_source\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::hazard_perception_v0::Hazard3DArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hazard_perception_v0::Hazard3DArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.hazards);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Hazard3DArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hazard_perception_v0::Hazard3DArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hazard_perception_v0::Hazard3DArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "hazards: ";
    if (v.hazards.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.hazards.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::hazard_perception_v0::Hazard3D_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.hazards[i]);
    }
    if (v.hazards.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAZARD_PERCEPTION_V0_MESSAGE_HAZARD3DARRAY_H
