// Generated by gencpp from file hazard_perception_v0/HazardDetection2DArray.msg
// DO NOT EDIT!


#ifndef HAZARD_PERCEPTION_V0_MESSAGE_HAZARDDETECTION2DARRAY_H
#define HAZARD_PERCEPTION_V0_MESSAGE_HAZARDDETECTION2DARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <hazard_perception_v0/HazardDetection2D.h>

namespace hazard_perception_v0
{
template <class ContainerAllocator>
struct HazardDetection2DArray_
{
  typedef HazardDetection2DArray_<ContainerAllocator> Type;

  HazardDetection2DArray_()
    : header()
    , image_width(0)
    , image_height(0)
    , detections()  {
    }
  HazardDetection2DArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , image_width(0)
    , image_height(0)
    , detections(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _image_width_type;
  _image_width_type image_width;

   typedef uint32_t _image_height_type;
  _image_height_type image_height;

   typedef std::vector< ::hazard_perception_v0::HazardDetection2D_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::hazard_perception_v0::HazardDetection2D_<ContainerAllocator> >> _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::hazard_perception_v0::HazardDetection2DArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hazard_perception_v0::HazardDetection2DArray_<ContainerAllocator> const> ConstPtr;

}; // struct HazardDetection2DArray_

typedef ::hazard_perception_v0::HazardDetection2DArray_<std::allocator<void> > HazardDetection2DArray;

typedef boost::shared_ptr< ::hazard_perception_v0::HazardDetection2DArray > HazardDetection2DArrayPtr;
typedef boost::shared_ptr< ::hazard_perception_v0::HazardDetection2DArray const> HazardDetection2DArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hazard_perception_v0::HazardDetection2DArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hazard_perception_v0::HazardDetection2DArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hazard_perception_v0::HazardDetection2DArray_<ContainerAllocator1> & lhs, const ::hazard_perception_v0::HazardDetection2DArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.image_width == rhs.image_width &&
    lhs.image_height == rhs.image_height &&
    lhs.detections == rhs.detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hazard_perception_v0::HazardDetection2DArray_<ContainerAllocator1> & lhs, const ::hazard_perception_v0::HazardDetection2DArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hazard_perception_v0

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hazard_perception_v0::HazardDetection2DArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hazard_perception_v0::HazardDetection2DArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hazard_perception_v0::HazardDetection2DArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hazard_perception_v0::HazardDetection2DArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hazard_perception_v0::HazardDetection2DArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hazard_perception_v0::HazardDetection2DArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hazard_perception_v0::HazardDetection2DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a54e8f144b5914c6a26823e2f0656b2a";
  }

  static const char* value(const ::hazard_perception_v0::HazardDetection2DArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa54e8f144b5914c6ULL;
  static const uint64_t static_value2 = 0xa26823e2f0656b2aULL;
};

template<class ContainerAllocator>
struct DataType< ::hazard_perception_v0::HazardDetection2DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hazard_perception_v0/HazardDetection2DArray";
  }

  static const char* value(const ::hazard_perception_v0::HazardDetection2DArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hazard_perception_v0::HazardDetection2DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"uint32 image_width\n"
"uint32 image_height\n"
"HazardDetection2D[] detections\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: hazard_perception_v0/HazardDetection2D\n"
"uint32 x\n"
"uint32 y\n"
"uint32 width\n"
"uint32 height\n"
"float32 center_x\n"
"float32 center_y\n"
"float32 area\n"
"float32 circularity\n"
"float32 aspect_ratio\n"
;
  }

  static const char* value(const ::hazard_perception_v0::HazardDetection2DArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hazard_perception_v0::HazardDetection2DArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.image_width);
      stream.next(m.image_height);
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HazardDetection2DArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hazard_perception_v0::HazardDetection2DArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hazard_perception_v0::HazardDetection2DArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "image_width: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.image_width);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "image_height: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.image_height);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "detections: ";
    if (v.detections.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::hazard_perception_v0::HazardDetection2D_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.detections[i]);
    }
    if (v.detections.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAZARD_PERCEPTION_V0_MESSAGE_HAZARDDETECTION2DARRAY_H
