// Generated by gencpp from file hazard_perception_v0/HazardDetection2D.msg
// DO NOT EDIT!


#ifndef HAZARD_PERCEPTION_V0_MESSAGE_HAZARDDETECTION2D_H
#define HAZARD_PERCEPTION_V0_MESSAGE_HAZARDDETECTION2D_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hazard_perception_v0
{
template <class ContainerAllocator>
struct HazardDetection2D_
{
  typedef HazardDetection2D_<ContainerAllocator> Type;

  HazardDetection2D_()
    : x(0)
    , y(0)
    , width(0)
    , height(0)
    , center_x(0.0)
    , center_y(0.0)
    , area(0.0)
    , circularity(0.0)
    , aspect_ratio(0.0)  {
    }
  HazardDetection2D_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , width(0)
    , height(0)
    , center_x(0.0)
    , center_y(0.0)
    , area(0.0)
    , circularity(0.0)
    , aspect_ratio(0.0)  {
  (void)_alloc;
    }



   typedef uint32_t _x_type;
  _x_type x;

   typedef uint32_t _y_type;
  _y_type y;

   typedef uint32_t _width_type;
  _width_type width;

   typedef uint32_t _height_type;
  _height_type height;

   typedef float _center_x_type;
  _center_x_type center_x;

   typedef float _center_y_type;
  _center_y_type center_y;

   typedef float _area_type;
  _area_type area;

   typedef float _circularity_type;
  _circularity_type circularity;

   typedef float _aspect_ratio_type;
  _aspect_ratio_type aspect_ratio;





  typedef boost::shared_ptr< ::hazard_perception_v0::HazardDetection2D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hazard_perception_v0::HazardDetection2D_<ContainerAllocator> const> ConstPtr;

}; // struct HazardDetection2D_

typedef ::hazard_perception_v0::HazardDetection2D_<std::allocator<void> > HazardDetection2D;

typedef boost::shared_ptr< ::hazard_perception_v0::HazardDetection2D > HazardDetection2DPtr;
typedef boost::shared_ptr< ::hazard_perception_v0::HazardDetection2D const> HazardDetection2DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hazard_perception_v0::HazardDetection2D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hazard_perception_v0::HazardDetection2D_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hazard_perception_v0::HazardDetection2D_<ContainerAllocator1> & lhs, const ::hazard_perception_v0::HazardDetection2D_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height &&
    lhs.center_x == rhs.center_x &&
    lhs.center_y == rhs.center_y &&
    lhs.area == rhs.area &&
    lhs.circularity == rhs.circularity &&
    lhs.aspect_ratio == rhs.aspect_ratio;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hazard_perception_v0::HazardDetection2D_<ContainerAllocator1> & lhs, const ::hazard_perception_v0::HazardDetection2D_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hazard_perception_v0

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hazard_perception_v0::HazardDetection2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hazard_perception_v0::HazardDetection2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hazard_perception_v0::HazardDetection2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hazard_perception_v0::HazardDetection2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hazard_perception_v0::HazardDetection2D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hazard_perception_v0::HazardDetection2D_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hazard_perception_v0::HazardDetection2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "72b181939be57fb98fb1cb0af591360f";
  }

  static const char* value(const ::hazard_perception_v0::HazardDetection2D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x72b181939be57fb9ULL;
  static const uint64_t static_value2 = 0x8fb1cb0af591360fULL;
};

template<class ContainerAllocator>
struct DataType< ::hazard_perception_v0::HazardDetection2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hazard_perception_v0/HazardDetection2D";
  }

  static const char* value(const ::hazard_perception_v0::HazardDetection2D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hazard_perception_v0::HazardDetection2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 x\n"
"uint32 y\n"
"uint32 width\n"
"uint32 height\n"
"float32 center_x\n"
"float32 center_y\n"
"float32 area\n"
"float32 circularity\n"
"float32 aspect_ratio\n"
;
  }

  static const char* value(const ::hazard_perception_v0::HazardDetection2D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hazard_perception_v0::HazardDetection2D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.center_x);
      stream.next(m.center_y);
      stream.next(m.area);
      stream.next(m.circularity);
      stream.next(m.aspect_ratio);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HazardDetection2D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hazard_perception_v0::HazardDetection2D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hazard_perception_v0::HazardDetection2D_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "width: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.width);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "height: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.height);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "center_x: ";
    Printer<float>::stream(s, indent + "  ", v.center_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "center_y: ";
    Printer<float>::stream(s, indent + "  ", v.center_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "area: ";
    Printer<float>::stream(s, indent + "  ", v.area);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "circularity: ";
    Printer<float>::stream(s, indent + "  ", v.circularity);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "aspect_ratio: ";
    Printer<float>::stream(s, indent + "  ", v.aspect_ratio);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAZARD_PERCEPTION_V0_MESSAGE_HAZARDDETECTION2D_H
