# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hazard_perception/HazardDetection2D.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class HazardDetection2D(genpy.Message):
  _md5sum = "72b181939be57fb98fb1cb0af591360f"
  _type = "hazard_perception/HazardDetection2D"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint32 x
uint32 y
uint32 width
uint32 height
float32 center_x
float32 center_y
float32 area
float32 circularity
float32 aspect_ratio
"""
  __slots__ = ['x','y','width','height','center_x','center_y','area','circularity','aspect_ratio']
  _slot_types = ['uint32','uint32','uint32','uint32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x,y,width,height,center_x,center_y,area,circularity,aspect_ratio

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(HazardDetection2D, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = 0
      if self.y is None:
        self.y = 0
      if self.width is None:
        self.width = 0
      if self.height is None:
        self.height = 0
      if self.center_x is None:
        self.center_x = 0.
      if self.center_y is None:
        self.center_y = 0.
      if self.area is None:
        self.area = 0.
      if self.circularity is None:
        self.circularity = 0.
      if self.aspect_ratio is None:
        self.aspect_ratio = 0.
    else:
      self.x = 0
      self.y = 0
      self.width = 0
      self.height = 0
      self.center_x = 0.
      self.center_y = 0.
      self.area = 0.
      self.circularity = 0.
      self.aspect_ratio = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4I5f().pack(_x.x, _x.y, _x.width, _x.height, _x.center_x, _x.center_y, _x.area, _x.circularity, _x.aspect_ratio))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 36
      (_x.x, _x.y, _x.width, _x.height, _x.center_x, _x.center_y, _x.area, _x.circularity, _x.aspect_ratio,) = _get_struct_4I5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4I5f().pack(_x.x, _x.y, _x.width, _x.height, _x.center_x, _x.center_y, _x.area, _x.circularity, _x.aspect_ratio))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 36
      (_x.x, _x.y, _x.width, _x.height, _x.center_x, _x.center_y, _x.area, _x.circularity, _x.aspect_ratio,) = _get_struct_4I5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4I5f = None
def _get_struct_4I5f():
    global _struct_4I5f
    if _struct_4I5f is None:
        _struct_4I5f = struct.Struct("<4I5f")
    return _struct_4I5f
