// Generated by gencpp from file hazard_perception/Hazard3D.msg
// DO NOT EDIT!


#ifndef HAZARD_PERCEPTION_MESSAGE_HAZARD3D_H
#define HAZARD_PERCEPTION_MESSAGE_HAZARD3D_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace hazard_perception
{
template <class ContainerAllocator>
struct Hazard3D_
{
  typedef Hazard3D_<ContainerAllocator> Type;

  Hazard3D_()
    : id(0)
    , position()
    , confidence(0.0)
    , observation_count(0)
    , confirmed(false)
    , localization_source()  {
    }
  Hazard3D_(const ContainerAllocator& _alloc)
    : id(0)
    , position(_alloc)
    , confidence(0.0)
    , observation_count(0)
    , confirmed(false)
    , localization_source(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef uint32_t _observation_count_type;
  _observation_count_type observation_count;

   typedef uint8_t _confirmed_type;
  _confirmed_type confirmed;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _localization_source_type;
  _localization_source_type localization_source;





  typedef boost::shared_ptr< ::hazard_perception::Hazard3D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hazard_perception::Hazard3D_<ContainerAllocator> const> ConstPtr;

}; // struct Hazard3D_

typedef ::hazard_perception::Hazard3D_<std::allocator<void> > Hazard3D;

typedef boost::shared_ptr< ::hazard_perception::Hazard3D > Hazard3DPtr;
typedef boost::shared_ptr< ::hazard_perception::Hazard3D const> Hazard3DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hazard_perception::Hazard3D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hazard_perception::Hazard3D_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hazard_perception::Hazard3D_<ContainerAllocator1> & lhs, const ::hazard_perception::Hazard3D_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.position == rhs.position &&
    lhs.confidence == rhs.confidence &&
    lhs.observation_count == rhs.observation_count &&
    lhs.confirmed == rhs.confirmed &&
    lhs.localization_source == rhs.localization_source;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hazard_perception::Hazard3D_<ContainerAllocator1> & lhs, const ::hazard_perception::Hazard3D_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hazard_perception

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hazard_perception::Hazard3D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hazard_perception::Hazard3D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hazard_perception::Hazard3D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hazard_perception::Hazard3D_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hazard_perception::Hazard3D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hazard_perception::Hazard3D_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hazard_perception::Hazard3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2af06c5e740031a3e6b4af89771e5573";
  }

  static const char* value(const ::hazard_perception::Hazard3D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2af06c5e740031a3ULL;
  static const uint64_t static_value2 = 0xe6b4af89771e5573ULL;
};

template<class ContainerAllocator>
struct DataType< ::hazard_perception::Hazard3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hazard_perception/Hazard3D";
  }

  static const char* value(const ::hazard_perception::Hazard3D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hazard_perception::Hazard3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 id\n"
"geometry_msgs/Point position\n"
"float32 confidence\n"
"uint32 observation_count\n"
"bool confirmed\n"
"string localization_source\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::hazard_perception::Hazard3D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hazard_perception::Hazard3D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.position);
      stream.next(m.confidence);
      stream.next(m.observation_count);
      stream.next(m.confirmed);
      stream.next(m.localization_source);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Hazard3D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hazard_perception::Hazard3D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hazard_perception::Hazard3D_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "position: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "observation_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.observation_count);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "confirmed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.confirmed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "localization_source: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.localization_source);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAZARD_PERCEPTION_MESSAGE_HAZARD3D_H
