(cl:defpackage building_generator_interfaces-srv
  (:use )
  (:export
   "CALLELEVATOR"
   "<CALLELEVATOR-REQUEST>"
   "CALLELEVATOR-REQUEST"
   "<CALLELEVATOR-RESPONSE>"
   "CALLELEVATOR-RESPONSE"
   "SETDOORSTATE"
   "<SETDOORSTATE-REQUEST>"
   "SETDOORSTATE-REQUEST"
   "<SETDOORSTATE-RESPONSE>"
   "SETDOORSTATE-RESPONSE"
  ))

