// Generated by gencpp from file building_generator_interfaces/CallElevatorRequest.msg
// DO NOT EDIT!


#ifndef BUILDING_GENERATOR_INTERFACES_MESSAGE_CALLELEVATORREQUEST_H
#define BUILDING_GENERATOR_INTERFACES_MESSAGE_CALLELEVATORREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace building_generator_interfaces
{
template <class ContainerAllocator>
struct CallElevatorRequest_
{
  typedef CallElevatorRequest_<ContainerAllocator> Type;

  CallElevatorRequest_()
    : elevator_id()
    , target_floor(0)
    , open_doors(false)  {
    }
  CallElevatorRequest_(const ContainerAllocator& _alloc)
    : elevator_id(_alloc)
    , target_floor(0)
    , open_doors(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _elevator_id_type;
  _elevator_id_type elevator_id;

   typedef int32_t _target_floor_type;
  _target_floor_type target_floor;

   typedef uint8_t _open_doors_type;
  _open_doors_type open_doors;





  typedef boost::shared_ptr< ::building_generator_interfaces::CallElevatorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::building_generator_interfaces::CallElevatorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CallElevatorRequest_

typedef ::building_generator_interfaces::CallElevatorRequest_<std::allocator<void> > CallElevatorRequest;

typedef boost::shared_ptr< ::building_generator_interfaces::CallElevatorRequest > CallElevatorRequestPtr;
typedef boost::shared_ptr< ::building_generator_interfaces::CallElevatorRequest const> CallElevatorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::building_generator_interfaces::CallElevatorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::building_generator_interfaces::CallElevatorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::building_generator_interfaces::CallElevatorRequest_<ContainerAllocator1> & lhs, const ::building_generator_interfaces::CallElevatorRequest_<ContainerAllocator2> & rhs)
{
  return lhs.elevator_id == rhs.elevator_id &&
    lhs.target_floor == rhs.target_floor &&
    lhs.open_doors == rhs.open_doors;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::building_generator_interfaces::CallElevatorRequest_<ContainerAllocator1> & lhs, const ::building_generator_interfaces::CallElevatorRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace building_generator_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::building_generator_interfaces::CallElevatorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::building_generator_interfaces::CallElevatorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::building_generator_interfaces::CallElevatorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::building_generator_interfaces::CallElevatorRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::building_generator_interfaces::CallElevatorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::building_generator_interfaces::CallElevatorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::building_generator_interfaces::CallElevatorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b0d444968ff6f7638a0dbaaddb632567";
  }

  static const char* value(const ::building_generator_interfaces::CallElevatorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb0d444968ff6f763ULL;
  static const uint64_t static_value2 = 0x8a0dbaaddb632567ULL;
};

template<class ContainerAllocator>
struct DataType< ::building_generator_interfaces::CallElevatorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "building_generator_interfaces/CallElevatorRequest";
  }

  static const char* value(const ::building_generator_interfaces::CallElevatorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::building_generator_interfaces::CallElevatorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string elevator_id\n"
"int32 target_floor\n"
"bool open_doors\n"
;
  }

  static const char* value(const ::building_generator_interfaces::CallElevatorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::building_generator_interfaces::CallElevatorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.elevator_id);
      stream.next(m.target_floor);
      stream.next(m.open_doors);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CallElevatorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::building_generator_interfaces::CallElevatorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::building_generator_interfaces::CallElevatorRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "elevator_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.elevator_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_floor: ";
    Printer<int32_t>::stream(s, indent + "  ", v.target_floor);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "open_doors: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.open_doors);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BUILDING_GENERATOR_INTERFACES_MESSAGE_CALLELEVATORREQUEST_H
