// Generated by gencpp from file building_generator_interfaces/CallElevator.msg
// DO NOT EDIT!


#ifndef BUILDING_GENERATOR_INTERFACES_MESSAGE_CALLELEVATOR_H
#define BUILDING_GENERATOR_INTERFACES_MESSAGE_CALLELEVATOR_H

#include <ros/service_traits.h>


#include <building_generator_interfaces/CallElevatorRequest.h>
#include <building_generator_interfaces/CallElevatorResponse.h>


namespace building_generator_interfaces
{

struct CallElevator
{

typedef CallElevatorRequest Request;
typedef CallElevatorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CallElevator
} // namespace building_generator_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::building_generator_interfaces::CallElevator > {
  static const char* value()
  {
    return "b2f9babc7642b34ecdc8d6d6e7e3cebf";
  }

  static const char* value(const ::building_generator_interfaces::CallElevator&) { return value(); }
};

template<>
struct DataType< ::building_generator_interfaces::CallElevator > {
  static const char* value()
  {
    return "building_generator_interfaces/CallElevator";
  }

  static const char* value(const ::building_generator_interfaces::CallElevator&) { return value(); }
};


// service_traits::MD5Sum< ::building_generator_interfaces::CallElevatorRequest> should match
// service_traits::MD5Sum< ::building_generator_interfaces::CallElevator >
template<>
struct MD5Sum< ::building_generator_interfaces::CallElevatorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::building_generator_interfaces::CallElevator >::value();
  }
  static const char* value(const ::building_generator_interfaces::CallElevatorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::building_generator_interfaces::CallElevatorRequest> should match
// service_traits::DataType< ::building_generator_interfaces::CallElevator >
template<>
struct DataType< ::building_generator_interfaces::CallElevatorRequest>
{
  static const char* value()
  {
    return DataType< ::building_generator_interfaces::CallElevator >::value();
  }
  static const char* value(const ::building_generator_interfaces::CallElevatorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::building_generator_interfaces::CallElevatorResponse> should match
// service_traits::MD5Sum< ::building_generator_interfaces::CallElevator >
template<>
struct MD5Sum< ::building_generator_interfaces::CallElevatorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::building_generator_interfaces::CallElevator >::value();
  }
  static const char* value(const ::building_generator_interfaces::CallElevatorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::building_generator_interfaces::CallElevatorResponse> should match
// service_traits::DataType< ::building_generator_interfaces::CallElevator >
template<>
struct DataType< ::building_generator_interfaces::CallElevatorResponse>
{
  static const char* value()
  {
    return DataType< ::building_generator_interfaces::CallElevator >::value();
  }
  static const char* value(const ::building_generator_interfaces::CallElevatorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BUILDING_GENERATOR_INTERFACES_MESSAGE_CALLELEVATOR_H
