// Generated by gencpp from file building_generator_interfaces/SetDoorStateResponse.msg
// DO NOT EDIT!


#ifndef BUILDING_GENERATOR_INTERFACES_MESSAGE_SETDOORSTATERESPONSE_H
#define BUILDING_GENERATOR_INTERFACES_MESSAGE_SETDOORSTATERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace building_generator_interfaces
{
template <class ContainerAllocator>
struct SetDoorStateResponse_
{
  typedef SetDoorStateResponse_<ContainerAllocator> Type;

  SetDoorStateResponse_()
    : accepted(false)
    , state()
    , message()  {
    }
  SetDoorStateResponse_(const ContainerAllocator& _alloc)
    : accepted(false)
    , state(_alloc)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _accepted_type;
  _accepted_type accepted;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _state_type;
  _state_type state;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::building_generator_interfaces::SetDoorStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::building_generator_interfaces::SetDoorStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetDoorStateResponse_

typedef ::building_generator_interfaces::SetDoorStateResponse_<std::allocator<void> > SetDoorStateResponse;

typedef boost::shared_ptr< ::building_generator_interfaces::SetDoorStateResponse > SetDoorStateResponsePtr;
typedef boost::shared_ptr< ::building_generator_interfaces::SetDoorStateResponse const> SetDoorStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::building_generator_interfaces::SetDoorStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::building_generator_interfaces::SetDoorStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::building_generator_interfaces::SetDoorStateResponse_<ContainerAllocator1> & lhs, const ::building_generator_interfaces::SetDoorStateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.accepted == rhs.accepted &&
    lhs.state == rhs.state &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::building_generator_interfaces::SetDoorStateResponse_<ContainerAllocator1> & lhs, const ::building_generator_interfaces::SetDoorStateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace building_generator_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::building_generator_interfaces::SetDoorStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::building_generator_interfaces::SetDoorStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::building_generator_interfaces::SetDoorStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::building_generator_interfaces::SetDoorStateResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::building_generator_interfaces::SetDoorStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::building_generator_interfaces::SetDoorStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::building_generator_interfaces::SetDoorStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0e5c296abb230eb14a2576256399997f";
  }

  static const char* value(const ::building_generator_interfaces::SetDoorStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0e5c296abb230eb1ULL;
  static const uint64_t static_value2 = 0x4a2576256399997fULL;
};

template<class ContainerAllocator>
struct DataType< ::building_generator_interfaces::SetDoorStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "building_generator_interfaces/SetDoorStateResponse";
  }

  static const char* value(const ::building_generator_interfaces::SetDoorStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::building_generator_interfaces::SetDoorStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool accepted\n"
"string state\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::building_generator_interfaces::SetDoorStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::building_generator_interfaces::SetDoorStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.accepted);
      stream.next(m.state);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetDoorStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::building_generator_interfaces::SetDoorStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::building_generator_interfaces::SetDoorStateResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "accepted: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.accepted);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BUILDING_GENERATOR_INTERFACES_MESSAGE_SETDOORSTATERESPONSE_H
