// Generated by gencpp from file building_generator_interfaces/SetDoorState.msg
// DO NOT EDIT!


#ifndef BUILDING_GENERATOR_INTERFACES_MESSAGE_SETDOORSTATE_H
#define BUILDING_GENERATOR_INTERFACES_MESSAGE_SETDOORSTATE_H

#include <ros/service_traits.h>


#include <building_generator_interfaces/SetDoorStateRequest.h>
#include <building_generator_interfaces/SetDoorStateResponse.h>


namespace building_generator_interfaces
{

struct SetDoorState
{

typedef SetDoorStateRequest Request;
typedef SetDoorStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetDoorState
} // namespace building_generator_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::building_generator_interfaces::SetDoorState > {
  static const char* value()
  {
    return "e5374c1c5454908412f943b22596890b";
  }

  static const char* value(const ::building_generator_interfaces::SetDoorState&) { return value(); }
};

template<>
struct DataType< ::building_generator_interfaces::SetDoorState > {
  static const char* value()
  {
    return "building_generator_interfaces/SetDoorState";
  }

  static const char* value(const ::building_generator_interfaces::SetDoorState&) { return value(); }
};


// service_traits::MD5Sum< ::building_generator_interfaces::SetDoorStateRequest> should match
// service_traits::MD5Sum< ::building_generator_interfaces::SetDoorState >
template<>
struct MD5Sum< ::building_generator_interfaces::SetDoorStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::building_generator_interfaces::SetDoorState >::value();
  }
  static const char* value(const ::building_generator_interfaces::SetDoorStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::building_generator_interfaces::SetDoorStateRequest> should match
// service_traits::DataType< ::building_generator_interfaces::SetDoorState >
template<>
struct DataType< ::building_generator_interfaces::SetDoorStateRequest>
{
  static const char* value()
  {
    return DataType< ::building_generator_interfaces::SetDoorState >::value();
  }
  static const char* value(const ::building_generator_interfaces::SetDoorStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::building_generator_interfaces::SetDoorStateResponse> should match
// service_traits::MD5Sum< ::building_generator_interfaces::SetDoorState >
template<>
struct MD5Sum< ::building_generator_interfaces::SetDoorStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::building_generator_interfaces::SetDoorState >::value();
  }
  static const char* value(const ::building_generator_interfaces::SetDoorStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::building_generator_interfaces::SetDoorStateResponse> should match
// service_traits::DataType< ::building_generator_interfaces::SetDoorState >
template<>
struct DataType< ::building_generator_interfaces::SetDoorStateResponse>
{
  static const char* value()
  {
    return DataType< ::building_generator_interfaces::SetDoorState >::value();
  }
  static const char* value(const ::building_generator_interfaces::SetDoorStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BUILDING_GENERATOR_INTERFACES_MESSAGE_SETDOORSTATE_H
