// Generated by gencpp from file building_generator_interfaces/SetDoorStateRequest.msg
// DO NOT EDIT!


#ifndef BUILDING_GENERATOR_INTERFACES_MESSAGE_SETDOORSTATEREQUEST_H
#define BUILDING_GENERATOR_INTERFACES_MESSAGE_SETDOORSTATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace building_generator_interfaces
{
template <class ContainerAllocator>
struct SetDoorStateRequest_
{
  typedef SetDoorStateRequest_<ContainerAllocator> Type;

  SetDoorStateRequest_()
    : door_id()
    , open(false)  {
    }
  SetDoorStateRequest_(const ContainerAllocator& _alloc)
    : door_id(_alloc)
    , open(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _door_id_type;
  _door_id_type door_id;

   typedef uint8_t _open_type;
  _open_type open;





  typedef boost::shared_ptr< ::building_generator_interfaces::SetDoorStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::building_generator_interfaces::SetDoorStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetDoorStateRequest_

typedef ::building_generator_interfaces::SetDoorStateRequest_<std::allocator<void> > SetDoorStateRequest;

typedef boost::shared_ptr< ::building_generator_interfaces::SetDoorStateRequest > SetDoorStateRequestPtr;
typedef boost::shared_ptr< ::building_generator_interfaces::SetDoorStateRequest const> SetDoorStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::building_generator_interfaces::SetDoorStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::building_generator_interfaces::SetDoorStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::building_generator_interfaces::SetDoorStateRequest_<ContainerAllocator1> & lhs, const ::building_generator_interfaces::SetDoorStateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.door_id == rhs.door_id &&
    lhs.open == rhs.open;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::building_generator_interfaces::SetDoorStateRequest_<ContainerAllocator1> & lhs, const ::building_generator_interfaces::SetDoorStateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace building_generator_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::building_generator_interfaces::SetDoorStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::building_generator_interfaces::SetDoorStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::building_generator_interfaces::SetDoorStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::building_generator_interfaces::SetDoorStateRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::building_generator_interfaces::SetDoorStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::building_generator_interfaces::SetDoorStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::building_generator_interfaces::SetDoorStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "20f6b07b5c0945c531e68f4e6d4076be";
  }

  static const char* value(const ::building_generator_interfaces::SetDoorStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x20f6b07b5c0945c5ULL;
  static const uint64_t static_value2 = 0x31e68f4e6d4076beULL;
};

template<class ContainerAllocator>
struct DataType< ::building_generator_interfaces::SetDoorStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "building_generator_interfaces/SetDoorStateRequest";
  }

  static const char* value(const ::building_generator_interfaces::SetDoorStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::building_generator_interfaces::SetDoorStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string door_id\n"
"bool open\n"
;
  }

  static const char* value(const ::building_generator_interfaces::SetDoorStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::building_generator_interfaces::SetDoorStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.door_id);
      stream.next(m.open);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetDoorStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::building_generator_interfaces::SetDoorStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::building_generator_interfaces::SetDoorStateRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "door_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.door_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "open: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.open);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BUILDING_GENERATOR_INTERFACES_MESSAGE_SETDOORSTATEREQUEST_H
